apiVersion: v1
kind: Service
metadata:
  name: kled-io-ecosystem-loadbalancer
  namespace: kled-io-ecosystem
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: 10443
      protocol: TCP
  selector:
    app: loft
